import Head from "next/head";
import Image from "next/image";

export default function PageLayout({
  children,
  title = "Notes App",
}: {
  children: any;
  title?: string;
}) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col bg-gradient-to-br from-white via-stone-100 to-slate-200 min-h-screen">
        <header className="px-3 py-5">
          <nav className="max-w-7xl mx-auto font-bold text-gray-800 text-4xl">NotesApp</nav>
        </header>

        <main className="container max-w-6xl flex-grow mx-auto p-7">
          {children}
        </main>
        <footer className="flex flex-col items-center pb-4">
          Powered by{" "}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </footer>
      </div>
    </>
  );
}
